### ISSUE TITLE
Allow array inputs for search functions

### ISSUE THREAD

**Issue by hombit** [cds-astro/cds-healpix-python#25]
It would be beneficial to have an efficient method for executing multiple cone, polygon, and elliptical searches with a single function call. This would shift the looping over the regions from Python to Rust, resulting in improved performance.

**Comment by fxpineau** [comment]
@hombit 
Are you interested in the ''fully_covered" flag?
If not, what about having the single-moc-from-multiple-cone/polygone/... functionalities in MOCPy?
The main point is that computing the union of MOCs (moc lib) is much faster than computing the union of B-MOCs (healpix lib). And, if you want the list of the cells at the MOC higher resolution, you can use [MOC.flatten()](fully_covered).

**Comment by hombit** [comment]
This sounds good to me! Feel free to close this issue if you don't need it for tracking
