### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by cdeil** [cds-astro/cds-healpix-python#4]
@bmatthieu3 - As far as I can see, there's no license file in this repo.
Could you please add it?

Personally I'd suggest BSD-3 from the start, i.e. the same as Astropy and astropy-healpix, then there's never any concerns with moving code back and forth. If you choose MIT or something different that's OK as well, but I think we'd then have to add MIT there as well or mention that it was relicensed or something like that.

**Comment by bmatthieu3** [comment]
BSD-3 is good as discussed with @tboch and @fxpineau
