### ISSUE TITLE
Merge README and docs?

### ISSUE THREAD

**Issue by cdeil** [cds-astro/cds-healpix-python#5]
@bmatthieu3 - my recommendation would be to merge the README and the docs

Either way, although personally I prefer a very short README as in https://github.com/astropy/astropy-healpix and then to have everything in the Sphinx docs.
Devs will still have it locally, they just have to open up the RST files in `docs` instead of the README, not a huge deal IMO.

Currently you have to very extensive docs:

* https://cds-astro.github.io/cds-healpix-python/
* https://github.com/cds-astro/cds-healpix-python/blob/master/README.md

E.g. the nice simple examples in the README are not in the Sphinx docs.
And the nice install page from the Sphinx docs is not in the README.

If we fully merge this repo into astropy-healpix this might become irrelevant.
But it might be that developments here continue for some time, and people like me discover and bug you with e.g. rust build issues etc, and then having one docs instead of two is less work.

**Comment by bmatthieu3** [comment]
I want to remove the readme and only let the online doc.

> the nice simple examples in the README are not in the Sphinx docs.

In the API doc (like https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.healpix_to_lonlat.html#cdshealpix.nested.healpix_to_lonlat) there are doctests that are very similar to what is in the readme.
